### ISSUE TITLE
1.21 Upload on Modrinth is 1.21.1

### ISSUE THREAD

**Issue by Demadunk** [SauliusRam/explorers-camp#5]
Attempting to run the 1.21 download in 1.21 does not work and says it is 1.21.1

Mod 'Expedition Essentials' (expedition_essentials) 1.0.0 requires any version between 1.21.1 (inclusive) and 1.22-<br>(exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!

Hopefully not a code issue and you accidentally uploaded the wrong file

**Comment by SauliusRam** [comment]
Hello,  
Thank you for the insight! It turned out to be a code issue. I’ve already uploaded a new version of the mod for MC 1.21. Let me know if it works now!

**Comment by Demadunk** [comment]
I'll get back to you and test for bugs in six hours from now.

**Comment by Demadunk** [comment]
Newest patch works and currently testing it out further in a multiplayer setting.
